EXTRA_DIST += cruft/amos/module.mk

CRUFT_SOURCES += \
  cruft/amos/cacai.f \
  cruft/amos/cacon.f \
  cruft/amos/cbesh.f \
  cruft/amos/cbesi.f \
  cruft/amos/cbesj.f \
  cruft/amos/cbesk.f \
  cruft/amos/cbesy.f \
  cruft/amos/cbinu.f \
  cruft/amos/cbuni.f \
  cruft/amos/cbunk.f \
  cruft/amos/cunk1.f \
  cruft/amos/cunk2.f \
  cruft/amos/crati.f \
  cruft/amos/cshch.f \
  cruft/amos/cuni1.f \
  cruft/amos/cuoik.f \
  cruft/amos/cairy.f \
  cruft/amos/cbiry.f \
  cruft/amos/ckscl.f \
  cruft/amos/cs1s2.f \
  cruft/amos/cuchk.f \
  cruft/amos/cuni2.f \
  cruft/amos/cwrsk.f \
  cruft/amos/casyi.f \
  cruft/amos/cbknu.f \
  cruft/amos/cmlri.f \
  cruft/amos/cseri.f \
  cruft/amos/cunhj.f \
  cruft/amos/cunik.f \
  cruft/amos/dgamln.f \
  cruft/amos/gamln.f \
  cruft/amos/xzabs.f \
  cruft/amos/xzexp.f \
  cruft/amos/xzlog.f \
  cruft/amos/xzsqrt.f \
  cruft/amos/zacai.f \
  cruft/amos/zacon.f \
  cruft/amos/zairy.f \
  cruft/amos/zasyi.f \
  cruft/amos/zbesh.f \
  cruft/amos/zbesi.f \
  cruft/amos/zbesj.f \
  cruft/amos/zbesk.f \
  cruft/amos/zbesy.f \
  cruft/amos/zbinu.f \
  cruft/amos/zbiry.f \
  cruft/amos/zbknu.f \
  cruft/amos/zbuni.f \
  cruft/amos/zbunk.f \
  cruft/amos/zdiv.f \
  cruft/amos/zkscl.f \
  cruft/amos/zmlri.f \
  cruft/amos/zmlt.f \
  cruft/amos/zrati.f \
  cruft/amos/zs1s2.f \
  cruft/amos/zseri.f \
  cruft/amos/zshch.f \
  cruft/amos/zuchk.f \
  cruft/amos/zunhj.f \
  cruft/amos/zuni1.f \
  cruft/amos/zuni2.f \
  cruft/amos/zunik.f \
  cruft/amos/zunk1.f \
  cruft/amos/zunk2.f \
  cruft/amos/zuoik.f \
  cruft/amos/zwrsk.f
