# SMOP compiler -- Simple Matlab/Octave to Python compiler
# Copyright 2011-2013 Victor Leikehman

import sys,cPickle,glob,os
import re
import getopt
import lexer,parse,resolve,backend,options,rewrite,node,typeof

def usage():
    print "SMOP compiler version 0.23"
    print """Usage: smop [options] file-list
    Options:
    -V --version
    -X --exclude=FILES      Ignore files listed in comma-separated list FILES
    -h --help
    -o --output=FILENAME    By default create file named a.py
    -o- --output=-          Use standard output
    -s --strict             Stop on the first error
    -n --no-comments        Strip comments
    -v --verbose
"""

def main():
    try:
        opts, args = getopt.gnu_getopt(sys.argv[1:],
                                       "ho:vVsX:n", 
                                       [
                                        "exclude",
                                        "help",
                                        "output=",
                                        "strict",
                                        "no-comments",
                                        "verbose",
                                        "version",
                                       ])
    except getopt.GetoptError, err:
        # print help information and exit:
        print str(err) # will print something like "option -a not recognized"
        usage()
        sys.exit(2)

    exclude_list = []
    output = None
    verbose = 0
    strict = 0
    with_comments = True

    for o, a in opts:
        if o in ("-s", "--strict"):
            strict = 1
        elif o in ("-X", "--exclude"):
            exclude_list += a.split(",")
        elif o in ("-v", "--verbose"):
            verbose += 1
        elif o in ("-V", "--version"):
            print "SMOP compiler version 0.23"
            sys.exit()
        elif o in ("-h", "--help"):
            usage()
            sys.exit()
        elif o in ("-o", "--output"):
            output = a
        elif o in ("-n", "--no-comments"):
            with_comments = False
        else:
            assert False, "unhandled option"

    if not output:
        output = "a.py"
    fp = open(output,"w") if output != "-" else sys.stdout
    print >> fp, "# Autogenerated with SMOP version 0.23"
    print >> fp, "# " + " ".join(sys.argv)
    print >> fp, "from __future__ import division"
    print >> fp, "import numpy as np"
    print >> fp, "from scipy.io import loadmat,savemat"
    print >> fp, "import scipy.signal"
    print >> fp, "import os\n"

    #print >> fp, "from copy import copy as _copy"
    #print >> fp, "numpy.random.seed(0)"

    for pattern in args:
        for filename in glob.glob(os.path.expanduser(pattern)):
            if not filename.endswith(".m"):
                print "\tIngored file: '%s'" % filename
                continue
            if os.path.basename(filename) in exclude_list:
                print "\tExcluded file: '%s'" % filename
                continue
            print filename
            buf = open(filename).read()
            
            # move each comment alone on a line
            # to avoid errors by trailing comment
            # and minimally change parsing rules
            buf = re.sub("%+", "\n %", buf)
            
            func_list = parse.parse(buf if buf[-1]=='\n' else buf+'\n',
                                    with_comments)

            try:
                symtab = {}
                for func_obj in func_list: 
                    try:
                        func_name = func_obj.head.ident.name
                        symtab[func_name] = func_obj
                        print "\t",func_name
                    except AttributeError:
                        if verbose:
                            print "\tJunk ignored"
                        if strict:
                            return
                        continue
                    if options.do_resolve:
                        resolve.resolve(func_obj)

                if options.do_typeof:
                    for func_obj in func_list:
                        t = func_obj.apply([],symtab)

                if options.do_rewrite:
                    for func_obj in func_list:
                        rewrite.rewrite(func_obj)

                for func_obj in func_list:
                    s = backend.backend(func_obj)
                    print >> fp, s
            except Exception as ex:
                print repr(ex)
                if strict:
                    return


if __name__ == "__main__":
    main()
