# Autogenerated with SMOP 
from smop.core import *
# C:\Users\quentin\Documents\svn\Manatee\trunk\Manatee_1.0\Plot\Commands\Electrical\plot_currents.m

    
@function
def plot_currents(Input=None,Output=None,*args,**kwargs):
    varargin = plot_currents.varargin
    nargin = plot_currents.nargin

    #  PLOT_CURRENTS plots the stator and rotor currents distribution in
#  phase and bars
    
    # Module ID: EL.pp
# $Author: jean $
# $Rev: 538 $
# $Date: 2016-12-07 13:31:32 +0100 (mer., 07 dc. 2016) $
# @copyright (C) 2013- EOMYS ENGINEERING.
    
    # Required fields of Input:
    
    # Required fields of Output:
    
    # Parameters:
    
    # Return values:
    
    ##########START OF THE CODE###################################
    
    if not_(protection(randi(100),mfilename)):
        disp('WARNING, you don\'t have the license to run this plot function')
        disp('Please contact EOMYS to obtain a license')
        return
    
    if nargin == 0:
        evalin('caller','plot_currents(Input,Output);')
    else:
        #stator currents
        plot_scurrent_time(Input,Output)
        plot_rcurrent_time(Input,Output)
    