@c Copyright (C) 1996-2015 John W. Eaton
@c
@c This file is part of Octave.
@c
@c Octave is free software; you can redistribute it and/or modify it
@c under the terms of the GNU General Public License as published by the
@c Free Software Foundation; either version 3 of the License, or (at
@c your option) any later version.
@c
@c Octave is distributed in the hope that it will be useful, but WITHOUT
@c ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
@c FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
@c for more details.
@c
@c You should have received a copy of the GNU General Public License
@c along with Octave; see the file COPYING.  If not, see
@c <http://www.gnu.org/licenses/>.

@node Ranges, Nonlinear Functions, Matrix Factorizations, Top
@chapter Ranges
@cindex ranges

@deftypefn  {} {} Range (void)
@deftypefnx  {} {} Range (const Range &@var{r})
@deftypefnx  {} {} Range (double @var{b}, double @var{l})
@deftypefnx  {} {} Range (double @var{b}, double @var{l}, double @var{i})
@end deftypefn

@deftypefn {} double base (void) const
@deftypefnx {} double limit (void) const
@deftypefnx {} double inc (void) const
@end deftypefn

@deftypefn {} void set_base (double @var{b})
@deftypefnx {} void set_limit (double @var{l})
@deftypefnx {} void set_inc (double @var{i})
@end deftypefn

@deftypefn {} int nelem (void) const
@end deftypefn

@deftypefn {} double min (void) const
@deftypefnx {} double max (void) const
@end deftypefn

@deftypefn {} void sort (void)
@end deftypefn

@deftypefn {} {ostream&} {operator <<} (ostream &@var{os}, const Range &@var{r})
@deftypefnx {} {istream&} {operator >>} (istream &@var{is}, Range &@var{r})
@end deftypefn

@deftypefn {} void print_range (void)
@end deftypefn
